-- AlterTable
ALTER TABLE "Topic" ADD COLUMN     "easeFactor" DOUBLE PRECISION NOT NULL DEFAULT 2.5,
ADD COLUMN     "nextReviewAt" TIMESTAMP(3),
ADD COLUMN     "reviewInterval" DOUBLE PRECISION NOT NULL DEFAULT 0;
